//// <auto-generated />
//using System;
//using ControleProdutos.Infra.Data;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//namespace ControleProdutos.Infra.Migrations
//{
//    [DbContext(typeof(Contexto))]
//    partial class ContextoModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("ProductVersion", "5.0.10")
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("ControleProdutos.Entidades.Entidades.Produto", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Descricao")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Produto");
//                });

//            modelBuilder.Entity("ControleProdutos.Entidades.Entidades.ProdutoInsumo", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Insumo")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<Guid>("ProdutoId")
//                        .HasColumnType("uniqueidentifier");

//                    b.HasKey("Id");

//                    b.HasIndex("ProdutoId");

//                    b.ToTable("ProdutoInsumo");
//                });

//            modelBuilder.Entity("ControleProdutos.Entidades.Entidades.ProdutoInsumo", b =>
//                {
//                    b.HasOne("ControleProdutos.Entidades.Entidades.Produto", null)
//                        .WithMany("Insumos")
//                        .HasForeignKey("ProdutoId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("ControleProdutos.Entidades.Entidades.Produto", b =>
//                {
//                    b.Navigation("Insumos");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
